spring:
  application:
        name: demoservice
        news: null
  profiles:
      active: dev
  datasource:
      url: jdbc:mysql://localhost:3306/willblog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: "root"
      password: "89541926"
  jpa:
      hibernate:
          ddl-auto: update
      generate-ddl: true
      show-sql: true
server:
  port: 8003
  context-path: /

email: tranphuuanan@gmail.com
thread-pool: 10
